# YeboSell — Cloudflare Pages Static Assets
name = "yebosell"
compatibility_date = "2024-09-23"
account_id = "3ed4a36f8edbaa255c5d1bf30fd6169c"

[assets]
directory = "./"
not_found_handling = "single-page-application"
